/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectograficacionpp.figuras;
import java.awt.Color;
import java.awt.color.ColorSpace;
import proyectograficacionpp.transformaciones.*;
/**
 *
 * @author Fred
 */
public class pruebaDibujo extends javax.swing.JFrame {
    private DirectDrawDemo dir;
    
    private Punto p1,p2,p3,p4;
    private int px1,py1,px2,py2,x3,y3,x4,y4,nroPuntos,grosor;
    private Rectangulo rect;
    private Cuadrado cuad;
    private Linea l;
    private Triangulo t;
    private String col;
    
    /**
     * Creates new form pruebaDibujo
     */
    
    public pruebaDibujo() {
        initComponents();
        int x=panelDibujo.getLocation().x;
        int y=panelDibujo.getLocation().y;
        int anch=panelDibujo.getSize().width;
        int alt=panelDibujo.getSize().height;
        dir=new DirectDrawDemo(anch, alt);
        nroPuntos=0;
        px1=-1;
        px2=-1;
        py1=-1;
        py2=-1;
        x3=-1;
        y3=-1;
        x4=-1;
        y4=-1;
        grosor=1;
        panelDibujo.setOpaque(false);
        //Color.ORANGE;
        col="BLACK";
        listColores.addItem("BLACK");
        listColores.addItem("RED");
        listColores.addItem("BLUE");
        listColores.addItem("GREEN");
        listColores.addItem("YELLOW");
        listColores.addItem("GRAY");
        listColores.addItem("ORANGE");
        
        jlistGrosor.addItem("1");
        jlistGrosor.addItem("2");
        jlistGrosor.addItem("3");
        jlistGrosor.addItem("4");
        jlistGrosor.addItem("5");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panelDibujo = new javax.swing.JPanel();
        btnLinea = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnRectan = new javax.swing.JButton();
        listColores = new javax.swing.JComboBox<>();
        jlistGrosor = new javax.swing.JComboBox<>();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDibujo.setBackground(new java.awt.Color(255, 255, 255));
        panelDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDibujoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        panelDibujoLayout.setVerticalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        btnLinea.setText("linea");
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });

        btnCuadrado.setText("cuadrado");
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });

        btnTriangulo.setText("triangulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnRectan.setText("rectangulo");
        btnRectan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanActionPerformed(evt);
            }
        });

        listColores.setModel(new javax.swing.DefaultComboBoxModel<>());
        listColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listColoresActionPerformed(evt);
            }
        });

        jlistGrosor.setModel(new javax.swing.DefaultComboBoxModel<>());
        jlistGrosor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistGrosorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlistGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(listColores, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLinea)
                                .addGap(18, 18, 18)
                                .addComponent(btnRectan)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTriangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCuadrado)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlistGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTriangulo)
                    .addComponent(btnCuadrado))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinea)
                    .addComponent(btnRectan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDibujoMouseClicked
            // esto escucha cuando presiono el mouse
           
            nroPuntos=nroPuntos+1;
            switch(nroPuntos){
                case 1: px1=evt.getX();
                        py1=evt.getY();
                        System.out.println(px1 +" "+ py1);
                        break;
                case 2: px2=evt.getX();
                        py2=evt.getY();
                        System.out.println(px2 +" "+ py2);
                        break;
                case 3:x3=evt.getX();
                       y3=evt.getY();
                       break;
                case 4:x4=evt.getX();
                       y4=evt.getY();
                       break;
                default:
                    break;
            }
    }//GEN-LAST:event_panelDibujoMouseClicked

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        p4=new Punto(x4, y4);
        cuad=new Cuadrado(p1, 5);//un tamaño de los lados
        
        switch (col){
            case "BLACK":   dir.cuadrado(cuad, Color.BLACK);
                        break;
            case "ORANGE":  dir.cuadrado(cuad, Color.ORANGE);
                        break;
            case "RED":  dir.cuadrado(cuad, Color.RED);
                        break;
            case "BLUE":  dir.cuadrado(cuad, Color.BLUE);
                        break;
            case "GRAY":  dir.cuadrado(cuad, Color.GRAY);
                        break;
            case "YELLOW":  dir.cuadrado(cuad, Color.YELLOW);
                        break;    
            case "GREEN":  dir.cuadrado(cuad, Color.GREEN);
                        break;  
            default:
                dir.cuadrado(cuad, Color.BLACK);
                break;
        }
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnRectanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        p4=new Punto(x4, y4);
        rect = new Rectangulo(p1, p2); //solo 2 esquinas
        switch (col){
            case "BLACK":  dir.rectangulo(rect, Color.BLACK); 
                        break;
            case "ORANGE":  dir.rectangulo(rect, Color.ORANGE);
                        break;
            case "RED":  dir.rectangulo(rect, Color.RED);
                        break;
            case "BLUE":  dir.rectangulo(rect, Color.BLUE);
                        break;
            case "GRAY":  dir.rectangulo(rect, Color.GRAY);
                        break;
            case "YELLOW":  dir.rectangulo(rect, Color.YELLOW);
                        break;    
            case "GREEN":  dir.rectangulo(rect, Color.GREEN);
                        break;  
            default:
                dir.rectangulo(rect, Color.BLACK); 
                break;
        }
        
    }//GEN-LAST:event_btnRectanActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        t =new Triangulo(p1, p2, p3);
        dir.triangulo(t, Color.red);
         switch (col){
            case "BLACK":   dir.triangulo(t, Color.BLACK);
                        break;
            case "ORANGE":  dir.triangulo(t, Color.ORANGE);
                        break;
            case "RED":  dir.triangulo(t, Color.RED);
                        break;
            case "BLUE":  dir.triangulo(t, Color.BLUE);
                        break;
            case "GRAY":  dir.triangulo(t, Color.GRAY);
                        break;
            case "YELLOW":  dir.triangulo(t, Color.YELLOW);
                        break;    
            case "GREEN":  dir.triangulo(t, Color.GREEN);
                        break;  
            default:
                dir.triangulo(t, Color.BLACK);
                break;
        }
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        l=new Linea(p1, p2);
        
        switch (col){
            case "BLACK":   dir.lineaDDA(l, Color.BLACK);
                        break;
            case "ORANGE":  dir.lineaDDA(l, Color.ORANGE);
                        break;
            case "RED":  dir.lineaDDA(l, Color.RED);
                        break;
            case "BLUE":  dir.lineaDDA(l, Color.BLUE);
                        break;
            case "GRAY":  dir.lineaDDA(l, Color.GRAY);
                        break;
            case "YELLOW":  dir.lineaDDA(l, Color.YELLOW);
                        break;    
            case "GREEN":  dir.lineaDDA(l, Color.GREEN);
                        break;  
            default:
                dir.lineaDDA(l, Color.BLACK);
                break;
        }
    }//GEN-LAST:event_btnLineaActionPerformed

    private void listColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listColoresActionPerformed
        String coloSelec=(String) listColores.getSelectedItem();
        col=coloSelec;
        //System.out.println(col+" "); //si selecciona bien
    }//GEN-LAST:event_listColoresActionPerformed

    private void jlistGrosorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistGrosorActionPerformed
        int gros=Integer.parseInt((String)jlistGrosor.getSelectedItem());
        if(gros>0){
            grosor=gros;
            
        }
    }//GEN-LAST:event_jlistGrosorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaDibujo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnRectan;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jlistGrosor;
    private javax.swing.JComboBox<String> listColores;
    private javax.swing.JPanel panelDibujo;
    // End of variables declaration//GEN-END:variables
}
