/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectograficacionpp.figuras;
import java.awt.Color;
import java.awt.Component;
import java.awt.color.ColorSpace;
import proyectograficacionpp.transformaciones.*;
/**
 *
 * @author Fred
 */
public class pruebaDibujo extends javax.swing.JFrame {
    private DirectDrawDemo dir;
    
    private Punto p1,p2,p3,p4;
    private int px1,py1,px2,py2,x3,y3,x4,y4,nroPuntos,grosor;
    private Rectangulo rect;
    private Cuadrado cuad;
    private Linea l;
    private Triangulo t;
    private String col;
    
    /**
     * Creates new form pruebaDibujo
     */
    
    public pruebaDibujo() {
        initComponents();
        this.setLayout(null);
        int x=panelDibujo.getLocation().x;
        int y=panelDibujo.getLocation().y;
        int anch=panelDibujo.getSize().width;
        int alt=panelDibujo.getSize().height;
        panelDibujo.setVisible(false);
        dir = new DirectDrawDemo(anch, alt);
        dir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDibujoMouseClicked(evt);
            }
        });
        dir.setBounds(x, y, anch, alt);
        getContentPane().add(dir);
        panelDibujo.setBackground(Color.red);
        nroPuntos=0;
        px1=-1;
        px2=-1;
        py1=-1;
        py2=-1;
        x3=-1;
        y3=-1;
        x4=-1;
        y4=-1;
        grosor=1;

        //panelDibujo.setOpaque(false);

        //Color.ORANGE;
        col="BLACK";
        listColores.addItem("BLACK");
        listColores.addItem("RED");
        listColores.addItem("BLUE");
        listColores.addItem("GREEN");
        listColores.addItem("YELLOW");
        listColores.addItem("GRAY");
        listColores.addItem("ORANGE");
        
        jlistGrosor.addItem("1");
        jlistGrosor.addItem("2");
        jlistGrosor.addItem("3");
        jlistGrosor.addItem("4");
        jlistGrosor.addItem("5");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDibujo = new javax.swing.JPanel();
        pnlBotn = new javax.swing.JPanel();
        jlbP3 = new javax.swing.JLabel();
        jlbP4 = new javax.swing.JLabel();
        btnRectan = new javax.swing.JButton();
        jlbP2 = new javax.swing.JLabel();
        listColores = new javax.swing.JComboBox<>();
        jlistGrosor = new javax.swing.JComboBox<>();
        jComCantSegmento = new javax.swing.JComboBox<>();
        checkSegmentado = new java.awt.Checkbox();
        jlblP1 = new javax.swing.JLabel();
        jlblP2 = new javax.swing.JLabel();
        jlblP3 = new javax.swing.JLabel();
        btnLinea = new javax.swing.JButton();
        jlblP4 = new javax.swing.JLabel();
        btnCuadrado = new javax.swing.JButton();
        jlblGrosor = new javax.swing.JLabel();
        btnTriangulo = new javax.swing.JButton();
        jlbP1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtFlado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCirculo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFradio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDibujo.setBackground(new java.awt.Color(255, 255, 255));
        panelDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDibujoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        panelDibujoLayout.setVerticalGroup(
            panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        btnRectan.setText("rectangulo");
        btnRectan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanActionPerformed(evt);
            }
        });

        listColores.setModel(new javax.swing.DefaultComboBoxModel<>());
        listColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listColoresActionPerformed(evt);
            }
        });

        jlistGrosor.setModel(new javax.swing.DefaultComboBoxModel<>());
        jlistGrosor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistGrosorActionPerformed(evt);
            }
        });

        jComCantSegmento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6" }));
        jComCantSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComCantSegmentoActionPerformed(evt);
            }
        });

        checkSegmentado.setLabel("segmentado");
        checkSegmentado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkSegmentadoItemStateChanged(evt);
            }
        });

        jlblP1.setText("p1(x,y):");

        jlblP2.setText("p2(x,y):");

        jlblP3.setText("p3(x,y):");

        btnLinea.setText("linea");
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });

        jlblP4.setText("p4(x,y):");

        btnCuadrado.setText("cuadrado");
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });

        jlblGrosor.setText("grosor:");

        btnTriangulo.setText("triangulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtFlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFladoActionPerformed(evt);
            }
        });

        jLabel1.setText("Medida Lado:");

        btnCirculo.setText("circulo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        jLabel2.setText("Radio:");

        javax.swing.GroupLayout pnlBotnLayout = new javax.swing.GroupLayout(pnlBotn);
        pnlBotn.setLayout(pnlBotnLayout);
        pnlBotnLayout.setHorizontalGroup(
            pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotnLayout.createSequentialGroup()
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotnLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(btnTriangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCuadrado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLinea)
                        .addGap(18, 18, 18)
                        .addComponent(btnRectan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFlado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnlBotnLayout.createSequentialGroup()
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotnLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblGrosor)
                            .addGroup(pnlBotnLayout.createSequentialGroup()
                                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComCantSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlistGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlblP4))
                                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBotnLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(listColores, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkSegmentado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlBotnLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jlbP4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlBotnLayout.createSequentialGroup()
                                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotnLayout.createSequentialGroup()
                                        .addComponent(jlblP1)
                                        .addGap(18, 18, 18))
                                    .addGroup(pnlBotnLayout.createSequentialGroup()
                                        .addComponent(jlblP2)
                                        .addGap(18, 18, 18)))
                                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlBotnLayout.createSequentialGroup()
                                .addComponent(jlblP3)
                                .addGap(18, 18, 18)
                                .addComponent(jlbP3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBotnLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCirculo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFradio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(119, 119, 119))
        );
        pnlBotnLayout.setVerticalGroup(
            pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblP1)
                    .addComponent(jlbP1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblP3)
                    .addComponent(jlbP3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblP4)
                    .addComponent(jlbP4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jlblGrosor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlistGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSegmentado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComCantSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTriangulo)
                    .addComponent(btnCuadrado)
                    .addComponent(jLabel1)
                    .addComponent(txtFlado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLinea)
                    .addComponent(btnRectan))
                .addGap(19, 19, 19)
                .addGroup(pnlBotnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCirculo)
                    .addComponent(jLabel2)
                    .addComponent(txtFradio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(pnlBotn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pnlBotn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDibujoMouseClicked
            // esto escucha cuando presiono el mouse
           
            nroPuntos=nroPuntos+1;
            switch(nroPuntos){
                case 1: px1=evt.getX();
                        py1=evt.getY();
                        System.out.println(px1 +" "+ py1);
                        
                        jlbP1.setText("("+""+px1+","+py1+")");
                        break;
                case 2: px2=evt.getX();
                        py2=evt.getY();
                        System.out.println(px2 +" "+ py2);
                        
                        jlbP2.setText("("+""+px2+","+py2+")");
                        break;
                case 3:x3=evt.getX();
                       y3=evt.getY();
                       System.out.println(x3+" "+y3);
                       jlbP3.setText("("+""+x3+","+y3+")");
                       break;
                case 4:x4=evt.getX();
                       y4=evt.getY();
                       System.out.println(x4+" "+y4);
                       jlbP4.setText("("+""+x4+","+y4+")");
                       break;
                default:
                    break;
            }
    }//GEN-LAST:event_panelDibujoMouseClicked

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        p4=new Punto(x4, y4);
        int lado = Integer.parseInt(txtFlado.getText());
        cuad=new Cuadrado(p1, lado);//un tamaño de los lados
        
        switch (col){
            case "BLACK":   dir.cuadrado(cuad, Color.BLACK);
                        break;
            case "ORANGE":  dir.cuadrado(cuad, Color.ORANGE);
                        break;
            case "RED":  dir.cuadrado(cuad, Color.RED);
                        break;
            case "BLUE":  dir.cuadrado(cuad, Color.BLUE);
                        break;
            case "GRAY":  dir.cuadrado(cuad, Color.GRAY);
                        break;
            case "YELLOW":  dir.cuadrado(cuad, Color.YELLOW);
                        break;    
            case "GREEN":  dir.cuadrado(cuad, Color.GREEN);
                        break;  
            default:
                dir.cuadrado(cuad, Color.BLACK);
                break;
        }
        dir.updateUI();
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnRectanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        p4=new Punto(x4, y4);
        rect = new Rectangulo(p1, p2); //solo 2 esquinas
        switch (col){
            case "BLACK":  dir.rectangulo(rect, Color.BLACK); 
                        break;
            case "ORANGE":  dir.rectangulo(rect, Color.ORANGE);
                        break;
            case "RED":  dir.rectangulo(rect, Color.RED);
                        break;
            case "BLUE":  dir.rectangulo(rect, Color.BLUE);
                        break;
            case "GRAY":  dir.rectangulo(rect, Color.GRAY);
                        break;
            case "YELLOW":  dir.rectangulo(rect, Color.YELLOW);
                        break;    
            case "GREEN":  dir.rectangulo(rect, Color.GREEN);
                        break;  
            default:
                dir.rectangulo(rect, Color.BLACK); 
                break;
        }
        dir.updateUI();
    }//GEN-LAST:event_btnRectanActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        //dir = (DirectDrawDemo)panelDibujo; //hacer esto hace que crasee
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        p3=new Punto(x3, y3);
        t =new Triangulo(p1, p2, p3);
         switch (col){
            case "BLACK":   dir.triangulo(t, Color.BLACK);
                        break;
            case "ORANGE":  dir.triangulo(t, Color.ORANGE);
                        break;
            case "RED":  dir.triangulo(t, Color.RED);
                        break;
            case "BLUE":  dir.triangulo(t, Color.BLUE);
                        break;
            case "GRAY":  dir.triangulo(t, Color.GRAY);
                        break;
            case "YELLOW":  dir.triangulo(t, Color.YELLOW);
                        break;    
            case "GREEN":  dir.triangulo(t, Color.GREEN);
                        break;  
            default:
                dir.triangulo(t, Color.BLACK);
                break;
        }
        dir.updateUI();
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        p1=new Punto(px1, py1);
        p2=new Punto(px2, py2);
        l=new Linea(p1, p2);
        
        switch (col){
            case "BLACK":   dir.lineaDDA(l, Color.BLACK);
                        break;
            case "ORANGE":  dir.lineaDDA(l, Color.ORANGE);
                        break;
            case "RED":  dir.lineaDDA(l, Color.RED);
                        break;
            case "BLUE":  dir.lineaDDA(l, Color.BLUE);
                        break;
            case "GRAY":  dir.lineaDDA(l, Color.GRAY);
                        break;
            case "YELLOW":  dir.lineaDDA(l, Color.YELLOW);
                        break;    
            case "GREEN":  dir.lineaDDA(l, Color.GREEN);
                        break;  
            default:
                dir.lineaDDA(l, Color.BLACK);
                break;
        }
        dir.updateUI();
    }//GEN-LAST:event_btnLineaActionPerformed

    private void listColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listColoresActionPerformed
        String coloSelec=(String) listColores.getSelectedItem();
        col=coloSelec;
        
        //System.out.println(col+" "); //si selecciona bien
    }//GEN-LAST:event_listColoresActionPerformed

    private void jlistGrosorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistGrosorActionPerformed
        int gros=Integer.parseInt((String)jlistGrosor.getSelectedItem());
        if(gros>0){
            grosor=gros;
            dir.setGrosor(grosor);
        }
    }//GEN-LAST:event_jlistGrosorActionPerformed

    private void jComCantSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComCantSegmentoActionPerformed
        int separ=Integer.parseInt((String)jComCantSegmento.getSelectedItem());
        
        dir.setCantSeparad(separ); //cambiamos al estado que quieras
        //System.out.println(separ+"");
    }//GEN-LAST:event_jComCantSegmentoActionPerformed

    private void checkSegmentadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSegmentadoItemStateChanged
        
        boolean separar=checkSegmentado.getState();
        
        if(separar){
            dir.setEsSegmentado(separar); //aqui solo activamos y ya 
            //System.out.println(separar+"");
        }else{
            dir.setEsSegmentado(separar);
            //System.out.println(separar+"");
        }
    }//GEN-LAST:event_checkSegmentadoItemStateChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        dir.limpiarPant();
        dir.updateUI();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtFladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFladoActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        p1=new Punto(px1, py1);
        int radio = Integer.parseInt(txtFradio.getText());
        Circunferencia circulo = new Circunferencia(p1,radio);
        switch (col){
            case "BLACK":  dir.bresenham(circulo, Color.BLACK); 
                        break;
            case "ORANGE":  dir.bresenham(circulo, Color.ORANGE);
                        break;
            case "RED":  dir.bresenham(circulo, Color.RED);
                        break;
            case "BLUE":  dir.bresenham(circulo, Color.BLUE);
                        break;
            case "GRAY":  dir.bresenham(circulo, Color.GRAY);
                        break;
            case "YELLOW":  dir.bresenham(circulo, Color.YELLOW);
                        break;    
            case "GREEN":  dir.bresenham(circulo, Color.GREEN);
                        break;  
            default:
                dir.bresenham(circulo, Color.BLACK); 
                break;
        }
        dir.updateUI();
    }//GEN-LAST:event_btnCirculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaDibujo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnRectan;
    private javax.swing.JButton btnTriangulo;
    private java.awt.Checkbox checkSegmentado;
    private javax.swing.JComboBox<String> jComCantSegmento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbP1;
    private javax.swing.JLabel jlbP2;
    private javax.swing.JLabel jlbP3;
    private javax.swing.JLabel jlbP4;
    private javax.swing.JLabel jlblGrosor;
    private javax.swing.JLabel jlblP1;
    private javax.swing.JLabel jlblP2;
    private javax.swing.JLabel jlblP3;
    private javax.swing.JLabel jlblP4;
    private javax.swing.JComboBox<String> jlistGrosor;
    private javax.swing.JComboBox<String> listColores;
    private javax.swing.JPanel panelDibujo;
    private javax.swing.JPanel pnlBotn;
    private javax.swing.JTextField txtFlado;
    private javax.swing.JTextField txtFradio;
    // End of variables declaration//GEN-END:variables
}
